version: '3.1'

services:
  db:
    container_name: db.postgres
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'mydatabaseuser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'mydatabase'